### ISSUE TITLE
Linkage issue

### ISSUE THREAD

**Issue by MrBrentRogers** [trfunk/foundry-deduplicator-webp#2]
Use VanceCole's bulk-convert-to-webp.ps1 powershell script to convert all .png files to .webp

Link to https://github.com/VanceCole/macros/blob/main/imagemagick/bulk-convert-to-webp.ps1 is broken
Likely correct link: https://github.com/VanceCole/macros/blob/master/imagemagick/bulk-convert-to-webp.ps1

**Comment by trfunk** [comment]
Seems like it, thanks for the heads up. Went ahead and fixed it.
